/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    records: Record;
    apparel: Apparel;
    banners: Banner;
    artists: Artist;
    genres: Genre;
    categories: Category;
    media: Media;
    orders: Order;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    genres: {
      records: 'records';
    };
  };
  collectionsSelect: {
    records: RecordsSelect<false> | RecordsSelect<true>;
    apparel: ApparelSelect<false> | ApparelSelect<true>;
    banners: BannersSelect<false> | BannersSelect<true>;
    artists: ArtistsSelect<false> | ArtistsSelect<true>;
    genres: GenresSelect<false> | GenresSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    homepage: Homepage;
  };
  globalsSelect: {
    homepage: HomepageSelect<false> | HomepageSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Vinis, CDs e outros formatos de áudio.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "records".
 */
export interface Record {
  id: number;
  title: string;
  /**
   * Gerado automaticamente a partir do título.
   */
  slug: string;
  shortDescription: string;
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Valor em reais. Ex: 449.90
   */
  price: number;
  /**
   * Deixe vazio se não houver promoção. Ex: 299.90
   */
  salePrice?: number | null;
  stock: number;
  /**
   * Código único do produto.
   */
  sku: string;
  format: 'vinyl' | 'cd';
  /**
   * Prensagem especial. Só se aplica a formatos de vinil.
   */
  vinylModel?: ('black' | 'clear' | 'splatter' | 'picture_disc' | 'other') | null;
  /**
   * Descreva o modelo. Ex: Marmorizado Azul, Tie-Dye, Galaxy...
   */
  vinylModelCustom?: string | null;
  condition: 'new' | 'used';
  /**
   * Pode selecionar mais de uma. Ex: Raro + Importado.
   */
  situation?:
    | (
        | 'rare'
        | 'imported'
        | 'sealed'
        | 'collectible'
        | 'limited_edition'
        | 'anniversary_edition'
        | 'remastered'
        | 'colored_vinyl'
      )[]
    | null;
  artist: number | Artist;
  genre?: (number | null) | Genre;
  /**
   * Ano original de lançamento do álbum.
   */
  releaseYear?: number | null;
  /**
   * Ex: Atlantic, Warner, Som Livre.
   */
  recordLabel?: string | null;
  /**
   * Lista de faixas do disco.
   */
  tracklist?:
    | {
        /**
         * Ex: A1, A2, B1 (vinil) ou 1, 2, 3 (CD).
         */
        position?: string | null;
        title: string;
        /**
         * Ex: 3:45.
         */
        duration?: string | null;
        id?: string | null;
      }[]
    | null;
  images: {
    image: number | Media;
    altText?: string | null;
    id?: string | null;
  }[];
  /**
   * Exibe o selo "RARO" no card do produto.
   */
  isRare?: boolean | null;
  /**
   * Desmarque para ocultar o produto da loja sem excluir. Desativado automaticamente quando estoque chega a zero.
   */
  active?: boolean | null;
  /**
   * Usado para cálculo de frete.
   */
  weight?: number | null;
  /**
   * Em centímetros.
   */
  dimensions?: {
    height?: number | null;
    width?: number | null;
    depth?: number | null;
  };
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Cadastre os artistas e bandas dos produtos da loja.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "artists".
 */
export interface Artist {
  id: number;
  name: string;
  /**
   * Auto-generated from name. Can be overridden manually.
   */
  slug: string;
  photo?: (number | null) | Media;
  bio?: string | null;
  /**
   * Data de fundação da banda ou nascimento do artista. Usada para destacar automaticamente o artista mais próximo do aniversário na página de Artistas.
   */
  foundedAt?: string | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Biblioteca de imagens usadas nos produtos e banners.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  /**
   * Preenchido automaticamente após o upload.
   */
  cloudinaryURL?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Gêneros musicais (ex: Heavy Metal, Doom, Punk).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "genres".
 */
export interface Genre {
  id: number;
  name: string;
  /**
   * Gerado automaticamente a partir do nome.
   */
  slug: string;
  /**
   * Breve descrição do gênero musical.
   */
  description?: string | null;
  /**
   * Discos vinculados a este gênero (somente leitura).
   */
  records?: {
    docs?: (number | Record)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Camisetas, moletons, bonés, pôsteres e acessórios com controle de estoque por tamanho.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "apparel".
 */
export interface Apparel {
  id: number;
  title: string;
  /**
   * Gerado automaticamente a partir do nome.
   */
  slug: string;
  shortDescription: string;
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Valor em reais. Ex: 59.90
   */
  price: number;
  /**
   * Deixe vazio se não houver promoção. Ex: 39.90
   */
  salePrice?: number | null;
  /**
   * Código base do produto. Cada variante pode ter seu próprio SKU.
   */
  sku: string;
  apparelType: 'tshirt' | 'hoodie' | 'jacket' | 'cap' | 'belt' | 'poster' | 'patch' | 'accessory';
  condition: 'new' | 'used' | 'rare' | 'collectible';
  /**
   * Opcional. Preencha para camisetas e itens de bandas específicas.
   */
  artist?: (number | null) | Artist;
  category: number | Category;
  /**
   * Adicione uma linha por combinação de tamanho e cor. Use "Tamanho Único" para pôsteres, bonés e acessórios sem numeração.
   */
  variants: {
    size: 'PP' | 'P' | 'M' | 'G' | 'GG' | 'GGG' | 'unico';
    /**
     * Opcional. Ex: Preto, Branco, Cinza.
     */
    color?: string | null;
    /**
     * Opcional. Deixe vazio para usar o SKU base.
     */
    sku?: string | null;
    stock: number;
    id?: string | null;
  }[];
  /**
   * Calculado automaticamente como soma de todas as variantes.
   */
  totalStock?: number | null;
  images: {
    image: number | Media;
    altText?: string | null;
    id?: string | null;
  }[];
  /**
   * Marcar para destacar este produto na página inicial.
   */
  featured?: boolean | null;
  /**
   * Exibe o selo "RARO" no card do produto.
   */
  isRare?: boolean | null;
  /**
   * Desativado automaticamente quando o estoque total chega a zero.
   */
  active?: boolean | null;
  /**
   * Usado para cálculo de frete.
   */
  weight?: number | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Organize os produtos em categorias (ex: Rock, Jazz, Merchandise).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  /**
   * Auto-generated from name. Can be overridden manually.
   */
  slug: string;
  image?: (number | null) | Media;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Crie os banners do carrossel da home. Existem dois modos:
 *
 * ① BANNER DE DESIGN PRÓPRIO — Suba só a imagem (já com o texto desenhado nela). Deixe título e todos os outros campos em branco.
 *
 * ② BANNER COM TEXTO — Preencha título, subtítulo e link. A imagem é opcional: sem imagem o banner exibe fundo verde escuro com a logo da Elessar; com imagem ela aparece como fundo.
 *
 * Após criar, vá em "Página Inicial" para escolher quais banners aparecem e em que ordem.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "banners".
 */
export interface Banner {
  id: number;
  /**
   * DESIGN PRÓPRIO: suba a imagem já com texto e design prontos — deixe todos os campos abaixo em branco.
   *
   * BANNER COM TEXTO: use uma foto de fundo. Sem imagem = fundo verde escuro com logo.
   */
  image?: (number | null) | Media;
  /**
   * Texto principal. Deixe em branco se a imagem já tiver o texto desenhado.
   */
  title?: string | null;
  /**
   * Texto secundário abaixo do título. Opcional.
   */
  subtitle?: string | null;
  /**
   * Caminho interno (ex: /catalogo) ou URL externa. Deixe vazio para não exibir botão.
   */
  link?: string | null;
  /**
   * Ex: "Ver Promoções", "Comprar Agora". Padrão: "Explorar".
   */
  linkLabel?: string | null;
  active?: boolean | null;
  order?: number | null;
  startsAt?: string | null;
  endsAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Acompanhe e gerencie todos os pedidos da loja.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  /**
   * Gerado automaticamente. Formato: ER-<timestamp>.
   */
  orderNumber: string;
  customer: number | User;
  items: {
    product:
      | {
          relationTo: 'records';
          value: number | Record;
        }
      | {
          relationTo: 'apparel';
          value: number | Apparel;
        };
    /**
     * Obrigatório para vestuário. Ex: M, G, Tamanho Único.
     */
    variantSize?: string | null;
    /**
     * Obrigatório se o vestuário tiver opções de cor.
     */
    variantColor?: string | null;
    quantity: number;
    /**
     * Preço no momento da compra. Não muda com o produto.
     */
    unitPrice: number;
    productTitle: string;
    productSku: string;
    id?: string | null;
  }[];
  /**
   * Calculado automaticamente a partir dos itens.
   */
  subtotal: number;
  shipping?: number | null;
  discount?: number | null;
  /**
   * Calculado: subtotal + frete − desconto.
   */
  total: number;
  status: 'pending' | 'confirmed' | 'paid' | 'processing' | 'shipped' | 'delivered' | 'cancelled' | 'refunded';
  paymentMethod?: ('pix' | 'credit_card' | 'boleto' | 'other') | null;
  paymentStatus?: ('unpaid' | 'paid' | 'refunded' | 'chargeback') | null;
  /**
   * ID externo do gateway de pagamento.
   */
  paymentId?: string | null;
  /**
   * Snapshot do endereço no momento do pedido.
   */
  shippingAddress?: {
    street?: string | null;
    number?: string | null;
    complement?: string | null;
    neighborhood?: string | null;
    city?: string | null;
    state?: string | null;
    zipCode?: string | null;
  };
  /**
   * Notas internas do admin. Não visível ao cliente.
   */
  notes?: string | null;
  /**
   * Mensagem enviada pelo cliente no checkout.
   */
  customerNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Administradores e clientes da loja.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  phone?: string | null;
  /**
   * Formato: 000.000.000-00. Coletado no checkout para nota fiscal.
   */
  cpf?: string | null;
  birthDate?: string | null;
  role?: ('admin' | 'client') | null;
  _verified?: boolean | null;
  addresses?:
    | {
        label?: string | null;
        street: string;
        number: string;
        complement?: string | null;
        neighborhood: string;
        city: string;
        state:
          | 'AC'
          | 'AL'
          | 'AP'
          | 'AM'
          | 'BA'
          | 'CE'
          | 'DF'
          | 'ES'
          | 'GO'
          | 'MA'
          | 'MT'
          | 'MS'
          | 'MG'
          | 'PA'
          | 'PB'
          | 'PR'
          | 'PE'
          | 'PI'
          | 'RJ'
          | 'RN'
          | 'RS'
          | 'RO'
          | 'RR'
          | 'SC'
          | 'SP'
          | 'SE'
          | 'TO';
        zipCode: string;
        isDefault?: boolean | null;
        id?: string | null;
      }[]
    | null;
  wishlist?:
    | (
        | {
            relationTo: 'records';
            value: number | Record;
          }
        | {
            relationTo: 'apparel';
            value: number | Apparel;
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'records';
        value: number | Record;
      } | null)
    | ({
        relationTo: 'apparel';
        value: number | Apparel;
      } | null)
    | ({
        relationTo: 'banners';
        value: number | Banner;
      } | null)
    | ({
        relationTo: 'artists';
        value: number | Artist;
      } | null)
    | ({
        relationTo: 'genres';
        value: number | Genre;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "records_select".
 */
export interface RecordsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  shortDescription?: T;
  description?: T;
  price?: T;
  salePrice?: T;
  stock?: T;
  sku?: T;
  format?: T;
  vinylModel?: T;
  vinylModelCustom?: T;
  condition?: T;
  situation?: T;
  artist?: T;
  genre?: T;
  releaseYear?: T;
  recordLabel?: T;
  tracklist?:
    | T
    | {
        position?: T;
        title?: T;
        duration?: T;
        id?: T;
      };
  images?:
    | T
    | {
        image?: T;
        altText?: T;
        id?: T;
      };
  isRare?: T;
  active?: T;
  weight?: T;
  dimensions?:
    | T
    | {
        height?: T;
        width?: T;
        depth?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "apparel_select".
 */
export interface ApparelSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  shortDescription?: T;
  description?: T;
  price?: T;
  salePrice?: T;
  sku?: T;
  apparelType?: T;
  condition?: T;
  artist?: T;
  category?: T;
  variants?:
    | T
    | {
        size?: T;
        color?: T;
        sku?: T;
        stock?: T;
        id?: T;
      };
  totalStock?: T;
  images?:
    | T
    | {
        image?: T;
        altText?: T;
        id?: T;
      };
  featured?: T;
  isRare?: T;
  active?: T;
  weight?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "banners_select".
 */
export interface BannersSelect<T extends boolean = true> {
  image?: T;
  title?: T;
  subtitle?: T;
  link?: T;
  linkLabel?: T;
  active?: T;
  order?: T;
  startsAt?: T;
  endsAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "artists_select".
 */
export interface ArtistsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  photo?: T;
  bio?: T;
  foundedAt?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "genres_select".
 */
export interface GenresSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  records?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  image?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  cloudinaryURL?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  orderNumber?: T;
  customer?: T;
  items?:
    | T
    | {
        product?: T;
        variantSize?: T;
        variantColor?: T;
        quantity?: T;
        unitPrice?: T;
        productTitle?: T;
        productSku?: T;
        id?: T;
      };
  subtotal?: T;
  shipping?: T;
  discount?: T;
  total?: T;
  status?: T;
  paymentMethod?: T;
  paymentStatus?: T;
  paymentId?: T;
  shippingAddress?:
    | T
    | {
        street?: T;
        number?: T;
        complement?: T;
        neighborhood?: T;
        city?: T;
        state?: T;
        zipCode?: T;
      };
  notes?: T;
  customerNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  cpf?: T;
  birthDate?: T;
  role?: T;
  _verified?: T;
  addresses?:
    | T
    | {
        label?: T;
        street?: T;
        number?: T;
        complement?: T;
        neighborhood?: T;
        city?: T;
        state?: T;
        zipCode?: T;
        isDefault?: T;
        id?: T;
      };
  wishlist?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Tudo que aparece na página inicial da loja. Banners do carrossel e discos em destaque.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  /**
   * Selecione os banners que vão aparecer no carrossel da home, na ordem desejada. Para criar um novo banner, acesse a seção "Banners" no menu.
   */
  banners?: (number | Banner)[] | null;
  /**
   * Escolha até 3 discos para aparecer na seção "Destaques" da home. Arraste para reordenar.
   */
  featuredRecords?: (number | Record)[] | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  banners?: T;
  featuredRecords?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}