/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    records: Record;
    apparel: Apparel;
    banners: Banner;
    artists: Artist;
    genres: Genre;
    categories: Category;
    media: Media;
    orders: Order;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    genres: {
      records: 'records';
    };
  };
  collectionsSelect: {
    records: RecordsSelect<false> | RecordsSelect<true>;
    apparel: ApparelSelect<false> | ApparelSelect<true>;
    banners: BannersSelect<false> | BannersSelect<true>;
    artists: ArtistsSelect<false> | ArtistsSelect<true>;
    genres: GenresSelect<false> | GenresSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    homepage: Homepage;
    'configuracoes-gerais': ConfiguracoesGerai;
    whatsapp: Whatsapp;
    rodape: Rodape;
    'pagina-sobre-nos': PaginaSobreNo;
    'paginas-legais': PaginasLegai;
    'perguntas-frequentes': PerguntasFrequente;
    'configuracoes-de-frete': ConfiguracoesDeFrete;
    'seguranca-da-conta': SegurancaDaConta;
  };
  globalsSelect: {
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    'configuracoes-gerais': ConfiguracoesGeraisSelect<false> | ConfiguracoesGeraisSelect<true>;
    whatsapp: WhatsappSelect<false> | WhatsappSelect<true>;
    rodape: RodapeSelect<false> | RodapeSelect<true>;
    'pagina-sobre-nos': PaginaSobreNosSelect<false> | PaginaSobreNosSelect<true>;
    'paginas-legais': PaginasLegaisSelect<false> | PaginasLegaisSelect<true>;
    'perguntas-frequentes': PerguntasFrequentesSelect<false> | PerguntasFrequentesSelect<true>;
    'configuracoes-de-frete': ConfiguracoesDeFreteSelect<false> | ConfiguracoesDeFreteSelect<true>;
    'seguranca-da-conta': SegurancaDaContaSelect<false> | SegurancaDaContaSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Vinis, CDs e outros formatos de áudio.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "records".
 */
export interface Record {
  id: number;
  title: string;
  /**
   * Gerado automaticamente a partir do título.
   */
  slug: string;
  shortDescription: string;
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Valor em reais. Ex: 449.90
   */
  price: number;
  /**
   * Deixe vazio se não houver promoção. Ex: 299.90
   */
  salePrice?: number | null;
  stock: number;
  /**
   * Código único do produto.
   */
  sku: string;
  format: 'vinyl' | 'cd';
  /**
   * Prensagem especial. Só se aplica a formatos de vinil.
   */
  vinylModel?: ('black' | 'clear' | 'splatter' | 'picture_disc' | 'other') | null;
  /**
   * Descreva o modelo. Ex: Marmorizado Azul, Tie-Dye, Galaxy...
   */
  vinylModelCustom?: string | null;
  condition: 'new' | 'used';
  /**
   * Pode selecionar mais de uma. Ex: Raro + Importado.
   */
  situation?:
    | (
        | 'rare'
        | 'imported'
        | 'sealed'
        | 'collectible'
        | 'limited_edition'
        | 'anniversary_edition'
        | 'remastered'
        | 'colored_vinyl'
      )[]
    | null;
  artist: number | Artist;
  genre?: (number | null) | Genre;
  /**
   * Ano original de lançamento do álbum.
   */
  releaseYear?: number | null;
  /**
   * Ex: Atlantic, Warner, Som Livre.
   */
  recordLabel?: string | null;
  /**
   * Lista de faixas do disco.
   */
  tracklist?:
    | {
        /**
         * Ex: A1, A2, B1 (vinil) ou 1, 2, 3 (CD).
         */
        position?: string | null;
        title: string;
        /**
         * Ex: 3:45.
         */
        duration?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * A primeira foto é a que aparece no catálogo. Use "Adicionar" para incluir mais ângulos — o cliente passa entre elas com as setas na página do produto.
   */
  images: {
    /**
     * Foto QUADRADA (mesma largura e altura), no mínimo 1000 x 1000 pixels. Se a sua não for quadrada, use "Editar imagem" para recortar.
     */
    image: number | Media;
    /**
     * Opcional. O que aparece na foto — ajuda no Google e em leitores de tela.
     */
    altText?: string | null;
    id?: string | null;
  }[];
  /**
   * Exibe o selo "RARO" no card do produto.
   */
  isRare?: boolean | null;
  /**
   * Desmarque para ocultar o produto da loja sem excluir. Desativado automaticamente quando estoque chega a zero.
   */
  active?: boolean | null;
  /**
   * Usado para cálculo de frete.
   */
  weight?: number | null;
  /**
   * Em centímetros.
   */
  dimensions?: {
    height?: number | null;
    width?: number | null;
    depth?: number | null;
  };
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    /**
     * Opcional. Aparece quando o link é compartilhado no WhatsApp, Instagram ou Facebook. Formato deitado, 1200 x 630 pixels. Sem ela, o site usa a primeira foto do produto.
     */
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Cadastre os artistas e bandas dos produtos da loja.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "artists".
 */
export interface Artist {
  id: number;
  name: string;
  /**
   * Auto-generated from name. Can be overridden manually.
   */
  slug: string;
  /**
   * Foto QUADRADA, no mínimo 1000 x 1000 pixels. Depois de escolher, use "Editar imagem" e posicione o PONTO DE FOCO sobre o rosto (ou o centro do grupo): assim ele não é cortado nos cards nem no destaque da página de artistas.
   */
  photo?: (number | null) | Media;
  bio?: string | null;
  /**
   * O ano em que a banda se formou, ou em que o artista começou a carreira. Só o ano, quatro dígitos: 1968. Aparece na página do artista. Pode deixar vazio se não souber — é melhor vazio que errado.
   */
  anoDeFormacao?: number | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Todas as imagens do site. Aceita JPG, PNG, WebP e GIF. Depois de escolher o arquivo, use "Editar imagem" para RECORTAR (escolher o pedaço que aparece) e para posicionar o PONTO DE FOCO — a mirinha marca o que nunca pode ser cortado, e o site respeita esse ponto em qualquer formato (card quadrado, banner largo no computador, banner alto no celular). Prefira imagens grandes: no mínimo 1000 x 1000 pixels.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * O que aparece na imagem, em poucas palavras (ex: "Capa do disco Paranoid, do Black Sabbath"). Usada por leitores de tela e pelo Google. Se deixar vazio, preenchemos com o nome do arquivo.
   */
  alt?: string | null;
  /**
   * Preenchido automaticamente quando a imagem enviada é pequena demais.
   */
  avisoQualidade?: string | null;
  /**
   * Preenchido automaticamente após o upload.
   */
  cloudinaryURL?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Gêneros musicais (ex: Heavy Metal, Doom, Punk).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "genres".
 */
export interface Genre {
  id: number;
  name: string;
  /**
   * Gerado automaticamente a partir do nome.
   */
  slug: string;
  /**
   * Breve descrição do gênero musical.
   */
  description?: string | null;
  /**
   * Discos vinculados a este gênero (somente leitura).
   */
  records?: {
    docs?: (number | Record)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Camisetas, moletons, bonés, pôsteres e acessórios com controle de estoque por tamanho.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "apparel".
 */
export interface Apparel {
  id: number;
  title: string;
  /**
   * Gerado automaticamente a partir do nome.
   */
  slug: string;
  shortDescription: string;
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Valor em reais. Ex: 59.90
   */
  price: number;
  /**
   * Deixe vazio se não houver promoção. Ex: 39.90
   */
  salePrice?: number | null;
  /**
   * Código base do produto. Cada variante pode ter seu próprio SKU.
   */
  sku: string;
  apparelType: 'tshirt' | 'hoodie' | 'jacket' | 'cap' | 'belt' | 'poster' | 'patch' | 'accessory';
  condition: 'new' | 'used' | 'rare' | 'collectible';
  /**
   * Opcional. Preencha para camisetas e itens de bandas específicas.
   */
  artist?: (number | null) | Artist;
  category: number | Category;
  /**
   * Adicione uma linha por combinação de tamanho e cor. Use "Tamanho Único" para pôsteres, bonés e acessórios sem numeração.
   */
  variants: {
    size: 'PP' | 'P' | 'M' | 'G' | 'GG' | 'GGG' | 'unico';
    /**
     * Opcional. Ex: Preto, Branco, Cinza.
     */
    color?: string | null;
    /**
     * Opcional. Deixe vazio para usar o SKU base.
     */
    sku?: string | null;
    stock: number;
    id?: string | null;
  }[];
  /**
   * Calculado automaticamente como soma de todas as variantes.
   */
  totalStock?: number | null;
  /**
   * A primeira foto é a que aparece no catálogo. Use "Adicionar" para incluir frente, costas e detalhes — o cliente passa entre elas com as setas na página do produto.
   */
  images: {
    /**
     * Foto QUADRADA (mesma largura e altura), no mínimo 1000 x 1000 pixels. Se a sua não for quadrada, use "Editar imagem" para recortar.
     */
    image: number | Media;
    /**
     * Opcional. O que aparece na foto — ajuda no Google e em leitores de tela.
     */
    altText?: string | null;
    id?: string | null;
  }[];
  /**
   * Marcar para destacar este produto na página inicial.
   */
  featured?: boolean | null;
  /**
   * Exibe o selo "RARO" no card do produto.
   */
  isRare?: boolean | null;
  /**
   * Desativado automaticamente quando o estoque total chega a zero.
   */
  active?: boolean | null;
  /**
   * Usado para cálculo de frete.
   */
  weight?: number | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    /**
     * Opcional. Aparece quando o link é compartilhado no WhatsApp, Instagram ou Facebook. Formato deitado, 1200 x 630 pixels. Sem ela, o site usa a primeira foto do produto.
     */
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Organize os produtos em categorias (ex: Rock, Jazz, Merchandise).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  /**
   * Auto-generated from name. Can be overridden manually.
   */
  slug: string;
  image?: (number | null) | Media;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Crie os banners do carrossel da home. Existem dois modos:
 *
 * ① BANNER DE DESIGN PRÓPRIO — Suba só a imagem (já com o texto desenhado nela). Deixe título e todos os outros campos em branco.
 *
 * ② BANNER COM TEXTO — Preencha título, subtítulo e link; o site escreve por cima da arte. A imagem é opcional: sem imagem o banner exibe fundo verde escuro com a logo da Elessar.
 *
 * TAMANHO DAS ARTES: computador 2560 x 960 px · celular 1080 x 1350 px. O detalhamento está na descrição de cada campo, e o guia completo para quem desenha é o arquivo BANNERS.md.
 *
 * Após criar, vá em "Página Inicial" para escolher quais banners aparecem e em que ordem.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "banners".
 */
export interface Banner {
  id: number;
  /**
   * TAMANHO EXATO: 2560 x 960 pixels (proporção 8:3). Formato JPG ou WebP, no máximo 500 KB.
   *
   * ZONA SEGURA: deixe texto, logo e botão dentro dos 80% do meio da arte. As bordas podem ser cortadas em telas muito largas ou muito estreitas — o que estiver na beirada some.
   *
   * Se a arte sair de outro tamanho, o site ainda mostra, mas recorta sozinho e o resultado é imprevisível. Use o tamanho exato.
   *
   * Sem imagem, o banner exibe fundo escuro com a logo da Elessar.
   *
   * Depois de escolher, clique em "Editar imagem" e posicione o PONTO DE FOCO no que não pode ser cortado — é ele que o site respeita ao ajustar a arte a cada tela.
   */
  image?: (number | null) | Media;
  recorteDesktop?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * TAMANHO EXATO: 1080 x 1920 pixels (proporção 9:16). Formato JPG ou WebP, no máximo 400 KB.
   *
   * ZONA SEGURA: deixe texto, logo e botão dentro dos 80% do meio da arte. As bordas podem ser cortadas em telas muito largas ou muito estreitas — o que estiver na beirada some.
   *
   * Se a arte sair de outro tamanho, o site ainda mostra, mas recorta sozinho e o resultado é imprevisível. Use o tamanho exato.
   *
   * Deixando vazio, o site recorta a arte do computador no formato do celular, respeitando o ponto de foco. Isso resolve na maioria dos casos — mas se a arte tiver TEXTO desenhado, mande a versão de celular, senão o texto é cortado.
   */
  imageMobile?: (number | null) | Media;
  recorteMobile?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Preenchido sozinho quando alguma arte está fora do formato pedido. É só um aviso: o banner funciona mesmo assim, mas pode sair cortado diferente do que você desenhou.
   */
  avisoProporcao?: string | null;
  /**
   * Texto principal. Deixe em branco se a imagem já tiver o texto desenhado.
   */
  title?: string | null;
  /**
   * Texto secundário abaixo do título. Opcional.
   */
  subtitle?: string | null;
  /**
   * Caminho interno (ex: /catalogo) ou URL externa. Deixe vazio para não exibir botão.
   */
  link?: string | null;
  /**
   * Ex: "Ver Promoções", "Comprar Agora". Padrão: "Explorar".
   */
  linkLabel?: string | null;
  /**
   * Desmarque para tirar do ar sem apagar o banner — ele some da home e continua salvo aqui para você ligar de novo quando quiser. Melhor que apagar e ter que cadastrar tudo outra vez.
   */
  active?: boolean | null;
  /**
   * Deixe vazio para o banner entrar no ar assim que for ligado. Preencha para deixar uma promoção pronta com antecedência — ela aparece sozinha na hora marcada.
   */
  startsAt?: string | null;
  /**
   * Deixe vazio para o banner ficar até você desligar. Preencha em promoção com prazo: o banner some sozinho e você não corre o risco de anunciar oferta que já acabou.
   */
  endsAt?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Acompanhe e gerencie todos os pedidos da loja.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  /**
   * Gerado automaticamente. Formato: ER-<timestamp>.
   */
  orderNumber: string;
  customer: number | User;
  items: {
    product:
      | {
          relationTo: 'records';
          value: number | Record;
        }
      | {
          relationTo: 'apparel';
          value: number | Apparel;
        };
    /**
     * Obrigatório para vestuário. Ex: M, G, Tamanho Único.
     */
    variantSize?: string | null;
    /**
     * Obrigatório se o vestuário tiver opções de cor.
     */
    variantColor?: string | null;
    quantity: number;
    /**
     * Preço no momento da compra. Não muda com o produto.
     */
    unitPrice: number;
    productTitle: string;
    productSku: string;
    id?: string | null;
  }[];
  /**
   * Calculado automaticamente a partir dos itens.
   */
  subtotal: number;
  /**
   * Definido automaticamente pela opção de frete escolhida.
   */
  shipping?: number | null;
  /**
   * Opção de frete selecionada pelo cliente no checkout.
   */
  freteEscolhido?: {
    /**
     * Usado para emitir a etiqueta. Ex: 1=PAC, 2=SEDEX, 17=Mini Envios.
     */
    servicoId?: number | null;
    transportadora?: string | null;
    /**
     * Ex: PAC, SEDEX.
     */
    nome?: string | null;
    prazo?: number | null;
    /**
     * Já com o acréscimo embutido.
     */
    preco?: number | null;
  };
  discount?: number | null;
  /**
   * Calculado: subtotal + frete − desconto.
   */
  total: number;
  status: 'aguardando_pagamento' | 'pago' | 'etiqueta_criada' | 'enviado' | 'entregue' | 'cancelado' | 'reembolsado';
  paymentMethod?: ('pix' | 'credit_card' | 'boleto' | 'other') | null;
  paymentStatus?: ('unpaid' | 'paid' | 'refunded' | 'chargeback') | null;
  /**
   * ID externo do gateway de pagamento (legado).
   */
  paymentId?: string | null;
  /**
   * Preenchido automaticamente quando o pagamento for integrado (fase futura).
   */
  idPagamentoMercadoPago?: string | null;
  /**
   * Dados de quem recebe o pedido. Usados na etiqueta dos Correios.
   */
  destinatario?: {
    nome?: string | null;
    /**
     * Obrigatório para emissão da etiqueta.
     */
    cpf?: string | null;
    email?: string | null;
    telefone?: string | null;
    cep?: string | null;
    rua?: string | null;
    numero?: string | null;
    complemento?: string | null;
    bairro?: string | null;
    cidade?: string | null;
    uf?: string | null;
  };
  /**
   * Snapshot antigo do endereço. Pedidos novos usam o grupo "Destinatário".
   */
  shippingAddress?: {
    street?: string | null;
    number?: string | null;
    complement?: string | null;
    neighborhood?: string | null;
    city?: string | null;
    state?: string | null;
    zipCode?: string | null;
  };
  /**
   * Preenchido automaticamente quando a etiqueta é criada.
   */
  idEtiquetaSuperFrete?: string | null;
  /**
   * Acompanhamento da etiqueta na SuperFrete.
   */
  statusEtiqueta?: ('a_emitir' | 'emitida' | 'erro') | null;
  /**
   * Mensagem de erro caso a criação da etiqueta falhe.
   */
  erroEtiqueta?: string | null;
  /**
   * Preenchido quando disponível.
   */
  codigoRastreio?: string | null;
  /**
   * Notas internas do admin. Não visível ao cliente.
   */
  notes?: string | null;
  /**
   * Mensagem enviada pelo cliente no checkout.
   */
  customerNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Administradores e clientes da loja.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  phone?: string | null;
  /**
   * Formato: 000.000.000-00. Uma conta por CPF.
   */
  cpf: string;
  birthDate?: string | null;
  /**
   * Definido automaticamente: é admin quem estiver em ADMIN_EMAILS no .env do servidor. Para promover alguém, edite a variável e faça o deploy — não dá para mudar por aqui.
   */
  role?: ('admin' | 'client') | null;
  /**
   * O link enviado por e-mail vale 24 horas. Depois disso o cliente precisa pedir um novo pela loja.
   */
  verificacaoExpiraEm?: string | null;
  /**
   * Serve para limitar reenvios: um a cada minuto, no máximo cinco por hora. Evita que a conta de alguém vire ferramenta de spam.
   */
  verificacaoUltimoEnvioEm?: string | null;
  verificacaoTokenUsadoHash?: string | null;
  /**
   * Marcado no momento do cadastro. Sem este aceite a conta não é criada. Não pode ser alterado depois — é prova do que o cliente concordou.
   */
  aceitouTermos?: boolean | null;
  /**
   * Qual versão dos termos estava no ar quando o cliente se cadastrou. Quando você muda a versão em "Páginas de Regras", quem tem versão antiga passa a ser considerado pendente de novo aceite.
   */
  versaoTermosAceita?: string | null;
  /**
   * Momento exato em que o cliente aceitou, no horário do servidor.
   */
  dataHoraAceite?: string | null;
  /**
   * Endereço de rede de onde veio o cadastro. Guardado só para comprovar o aceite numa eventual contestação.
   */
  ipDoAceite?: string | null;
  /**
   * Código único calculado a partir do texto exato dos termos naquele momento. Serve para provar QUE TEXTO o cliente aceitou, e não apenas qual número de versão — se alguém editar o texto sem trocar a versão, este código passa a não bater.
   */
  hashDosTermosAceitos?: string | null;
  /**
   * OPCIONAL e separado do aceite dos termos, como manda a LGPD: consentimento de marketing não pode vir embutido no aceite obrigatório. O cliente pode ligar e desligar quando quiser.
   */
  aceitouComunicacoesMarketing?: boolean | null;
  /**
   * Últimas entradas nesta conta, da mais recente para a mais antiga. Preenchido automaticamente a cada login. A origem aparece encurtada de propósito — o endereço completo de rede de um cliente não precisa ficar guardado à vista.
   */
  acessosRecentes?:
    | {
        dataHora?: string | null;
        dispositivo?: string | null;
        local?: string | null;
        origem?: string | null;
        avisoEnviado?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Uso interno: é o que evita mandar aviso de acesso a cada login do mesmo aparelho.
   */
  dispositivosConhecidos?:
    | {
        impressao?: string | null;
        descricao?: string | null;
        avisadoEm?: string | null;
        ultimoAcessoEm?: string | null;
        id?: string | null;
      }[]
    | null;
  addresses?:
    | {
        label?: string | null;
        street: string;
        number: string;
        complement?: string | null;
        neighborhood: string;
        city: string;
        state:
          | 'AC'
          | 'AL'
          | 'AP'
          | 'AM'
          | 'BA'
          | 'CE'
          | 'DF'
          | 'ES'
          | 'GO'
          | 'MA'
          | 'MT'
          | 'MS'
          | 'MG'
          | 'PA'
          | 'PB'
          | 'PR'
          | 'PE'
          | 'PI'
          | 'RJ'
          | 'RN'
          | 'RS'
          | 'RO'
          | 'RR'
          | 'SC'
          | 'SP'
          | 'SE'
          | 'TO';
        zipCode: string;
        isDefault?: boolean | null;
        id?: string | null;
      }[]
    | null;
  wishlist?:
    | (
        | {
            relationTo: 'records';
            value: number | Record;
          }
        | {
            relationTo: 'apparel';
            value: number | Apparel;
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  _verified?: boolean | null;
  _verificationToken?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'records';
        value: number | Record;
      } | null)
    | ({
        relationTo: 'apparel';
        value: number | Apparel;
      } | null)
    | ({
        relationTo: 'banners';
        value: number | Banner;
      } | null)
    | ({
        relationTo: 'artists';
        value: number | Artist;
      } | null)
    | ({
        relationTo: 'genres';
        value: number | Genre;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "records_select".
 */
export interface RecordsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  shortDescription?: T;
  description?: T;
  price?: T;
  salePrice?: T;
  stock?: T;
  sku?: T;
  format?: T;
  vinylModel?: T;
  vinylModelCustom?: T;
  condition?: T;
  situation?: T;
  artist?: T;
  genre?: T;
  releaseYear?: T;
  recordLabel?: T;
  tracklist?:
    | T
    | {
        position?: T;
        title?: T;
        duration?: T;
        id?: T;
      };
  images?:
    | T
    | {
        image?: T;
        altText?: T;
        id?: T;
      };
  isRare?: T;
  active?: T;
  weight?: T;
  dimensions?:
    | T
    | {
        height?: T;
        width?: T;
        depth?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "apparel_select".
 */
export interface ApparelSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  shortDescription?: T;
  description?: T;
  price?: T;
  salePrice?: T;
  sku?: T;
  apparelType?: T;
  condition?: T;
  artist?: T;
  category?: T;
  variants?:
    | T
    | {
        size?: T;
        color?: T;
        sku?: T;
        stock?: T;
        id?: T;
      };
  totalStock?: T;
  images?:
    | T
    | {
        image?: T;
        altText?: T;
        id?: T;
      };
  featured?: T;
  isRare?: T;
  active?: T;
  weight?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "banners_select".
 */
export interface BannersSelect<T extends boolean = true> {
  image?: T;
  recorteDesktop?: T;
  imageMobile?: T;
  recorteMobile?: T;
  avisoProporcao?: T;
  title?: T;
  subtitle?: T;
  link?: T;
  linkLabel?: T;
  active?: T;
  startsAt?: T;
  endsAt?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "artists_select".
 */
export interface ArtistsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  photo?: T;
  bio?: T;
  anoDeFormacao?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "genres_select".
 */
export interface GenresSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  records?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  image?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  avisoQualidade?: T;
  cloudinaryURL?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  orderNumber?: T;
  customer?: T;
  items?:
    | T
    | {
        product?: T;
        variantSize?: T;
        variantColor?: T;
        quantity?: T;
        unitPrice?: T;
        productTitle?: T;
        productSku?: T;
        id?: T;
      };
  subtotal?: T;
  shipping?: T;
  freteEscolhido?:
    | T
    | {
        servicoId?: T;
        transportadora?: T;
        nome?: T;
        prazo?: T;
        preco?: T;
      };
  discount?: T;
  total?: T;
  status?: T;
  paymentMethod?: T;
  paymentStatus?: T;
  paymentId?: T;
  idPagamentoMercadoPago?: T;
  destinatario?:
    | T
    | {
        nome?: T;
        cpf?: T;
        email?: T;
        telefone?: T;
        cep?: T;
        rua?: T;
        numero?: T;
        complemento?: T;
        bairro?: T;
        cidade?: T;
        uf?: T;
      };
  shippingAddress?:
    | T
    | {
        street?: T;
        number?: T;
        complement?: T;
        neighborhood?: T;
        city?: T;
        state?: T;
        zipCode?: T;
      };
  idEtiquetaSuperFrete?: T;
  statusEtiqueta?: T;
  erroEtiqueta?: T;
  codigoRastreio?: T;
  notes?: T;
  customerNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  cpf?: T;
  birthDate?: T;
  role?: T;
  verificacaoExpiraEm?: T;
  verificacaoUltimoEnvioEm?: T;
  verificacaoTokenUsadoHash?: T;
  aceitouTermos?: T;
  versaoTermosAceita?: T;
  dataHoraAceite?: T;
  ipDoAceite?: T;
  hashDosTermosAceitos?: T;
  aceitouComunicacoesMarketing?: T;
  acessosRecentes?:
    | T
    | {
        dataHora?: T;
        dispositivo?: T;
        local?: T;
        origem?: T;
        avisoEnviado?: T;
        id?: T;
      };
  dispositivosConhecidos?:
    | T
    | {
        impressao?: T;
        descricao?: T;
        avisadoEm?: T;
        ultimoAcessoEm?: T;
        id?: T;
      };
  addresses?:
    | T
    | {
        label?: T;
        street?: T;
        number?: T;
        complement?: T;
        neighborhood?: T;
        city?: T;
        state?: T;
        zipCode?: T;
        isDefault?: T;
        id?: T;
      };
  wishlist?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  _verified?: T;
  _verificationToken?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Tudo que aparece na página inicial da loja. Banners do carrossel e discos em destaque.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  /**
   * Selecione os banners que vão aparecer no carrossel da home, na ordem desejada. Para criar um novo banner, acesse a seção "Banners" no menu.
   */
  banners?: (number | Banner)[] | null;
  /**
   * Quanto tempo cada banner fica na tela antes de passar para o próximo. O padrão é 6 segundos.
   *
   * Banner com texto para ler pede mais tempo: menos de 4 segundos não dá para ler uma frase e ainda reparar na imagem. Passar rápido demais também incomoda quem estava lendo. Se houver um banner só, este campo não tem efeito — ele fica parado.
   *
   * Mínimo 3, máximo 30 segundos.
   */
  tempoDoCarrossel?: number | null;
  /**
   * Escolha até 3 discos para aparecer na seção "Destaques" da home. Arraste para reordenar.
   */
  featuredRecords?: (number | Record)[] | null;
  /**
   * Escolha até 4 discos para a seção "Lançamentos Exclusivos" da home. Arraste para reordenar. Se ficar vazio, a seção não aparece.
   */
  exclusiveReleases?: (number | Record)[] | null;
  /**
   * Até 4 logos de bandas na home. Cada ícone leva ao catálogo filtrado por aquele artista. Use PNG com fundo transparente para o melhor resultado.
   */
  bandIcons?:
    | {
        image: number | Media;
        /**
         * Para onde o clique leva (catálogo filtrado por este artista).
         */
        artist: number | Artist;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Os dados da Elessar que aparecem espalhados pelo site inteiro: nome, contato, redes sociais e CNPJ. São preenchidos uma vez e mudam raramente. Como tudo vem daqui, corrigir o telefone neste lugar corrige em todas as páginas de uma vez.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "configuracoes-gerais".
 */
export interface ConfiguracoesGerai {
  id: number;
  /**
   * Usado no topo do site, na aba do navegador e quando alguém compartilha um link da loja.
   */
  nomeDaLoja: string;
  /**
   * Uma ou duas linhas que resumem a Elessar. Aparece no rodapé e é o texto que o Google mostra embaixo do nome do site nos resultados de busca. Exemplo: "Discos selecionados a mão. Metal pesado, rock, underground e cultura alternativa."
   */
  tagline?: string | null;
  /**
   * O endereço que o cliente usa para falar com a loja. Aparece no rodapé e nas páginas de trocas e entrega. Use um e-mail que você realmente acompanhe.
   */
  emailContato?: string | null;
  /**
   * Escreva do jeito que se lê: (19) 99123-4567. Este campo é só para mostrar na tela — o número que o botão de WhatsApp usa fica na tela "Botão de WhatsApp" e tem outro formato.
   */
  telefone?: string | null;
  /**
   * O endereço físico da loja, se tiver atendimento presencial. Aparece no rodapé. Deixe vazio se a loja for só online.
   */
  endereco?: string | null;
  /**
   * Exemplo: "Segunda a sexta, das 9h às 18h". Aparece no rodapé.
   */
  horarioAtendimento?: string | null;
  /**
   * O nome de usuário com @ ou o endereço completo do perfil. Os dois funcionam.
   */
  instagram?: string | null;
  /**
   * Endereço completo do canal. Opcional.
   */
  youtube?: string | null;
  /**
   * Endereço completo da página. Opcional.
   */
  facebook?: string | null;
  /**
   * O nome registrado da empresa, que costuma ser diferente do nome da loja. Opcional.
   */
  razaoSocial?: string | null;
  /**
   * Aparece no rodapé de todas as páginas. Mostrar o CNPJ passa confiança para quem está comprando pela primeira vez e é exigido na venda online.
   */
  cnpj?: string | null;
  /**
   * Desmarcado, nada aparece. Marque só enquanto o recado valer — tarja que fica meses no ar todo mundo aprende a ignorar.
   */
  avisoAtivo?: boolean | null;
  /**
   * Uma frase só, curta. Exemplo: "Pedidos feitos a partir de 20/12 serão postados em janeiro."
   */
  avisoTexto?: string | null;
  /**
   * Para onde o cliente vai se clicar na tarja. Opcional — sem link, a tarja é só um recado.
   */
  avisoLink?: string | null;
  /**
   * A partir desta data a tarja some sozinha, sem você precisar lembrar de voltar aqui. Deixe vazio para o aviso ficar até você desmarcar na mão.
   */
  avisoValidoAte?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * O botão verde de WhatsApp que fica flutuando no canto da tela, em todas as páginas da loja. Aqui você define para qual telefone ele leva e o que já vem escrito na conversa quando o cliente clica.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "whatsapp".
 */
export interface Whatsapp {
  id: number;
  /**
   * Desmarque para esconder o botão temporariamente — em férias, por exemplo, ou quando não houver ninguém para responder. Melhor esconder que deixar o cliente falando sozinho.
   */
  ativo?: boolean | null;
  /**
   * Escreva o número completo, só com dígitos, começando pelo 55 do Brasil: 55, DDD, telefone. Para (19) 99123-4567 escreva 5519991234567. Sem espaço, sem parênteses, sem traço.
   */
  numero: string;
  /**
   * Quando o cliente clica no botão, o WhatsApp abre com esta frase já digitada — ele só aperta enviar. Serve para você saber de onde a pessoa veio. Vale a pena ser específico: "Olá! Vim pelo site da Elessar Records." é melhor que "Oi".
   */
  mensagemPadrao: string;
  /**
   * Usada no lugar da mensagem acima quando a pessoa clica estando na página de um produto. Escreva {{produto}} onde quiser que o site encaixe o nome do disco ou da peça — ele troca sozinho. Assim você já abre a conversa sabendo do que se trata, em vez de perguntar "qual produto?". Se deixar vazio, vale a mensagem padrão em todo lugar.
   */
  mensagemNoProduto?: string | null;
  /**
   * Uma frase curta que aparece ao lado do botão quando o cliente passa o mouse por cima. Exemplo: "Fale conosco" ou "Tire sua dúvida".
   */
  textoDoBotao?: string | null;
  /**
   * Aparece junto do botão para o cliente saber quando esperar resposta. Exemplo: "Segunda a sexta, das 9h às 18h". Deixar isso claro evita a frustração de quem manda mensagem no domingo à noite e acha que foi ignorado. Pode deixar vazio.
   */
  horarioAtendimento?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * A faixa cinza no fim de todas as páginas da loja, com as listas de links. O CNPJ, o endereço, o telefone e as redes sociais que aparecem lá NÃO se editam aqui — eles vêm da tela "Dados da Loja", para você não ter que corrigir a mesma informação em dois lugares.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rodape".
 */
export interface Rodape {
  id: number;
  /**
   * Cada lista vira uma coluna do rodapé, lado a lado. O normal são duas ou três: uma com as partes da loja ("Catálogo", "Vestuário") e outra com informação ("Sobre a Loja", "Trocas e Devoluções"). No celular elas viram uma embaixo da outra. Arraste para trocar a ordem.
   */
  colunas?:
    | {
        /**
         * O nome em cima da coluna. Exemplo: "Loja" ou "Informações".
         */
        titulo: string;
        /**
         * Aparecem na ordem em que estiverem aqui. Arraste para reordenar.
         */
        links: {
          /**
           * O que o cliente lê e clica. Exemplo: "Trocas e Devoluções".
           */
          texto: string;
          /**
           * Para uma página da própria loja, escreva a partir da barra: /catalogo, /trocas, /sobre. Para um site de fora, o endereço completo começando com https://. Se estiver errado, o cliente cai numa página de erro — vale conferir clicando depois de salvar.
           */
          endereco: string;
          id?: string | null;
        }[];
        id?: string | null;
      }[]
    | null;
  /**
   * A frase da última linha do rodapé. O ano e o nome da loja o site coloca sozinho — escreva só o resto. Exemplo: "Todos os direitos reservados." vira "© 2026 Elessar Records. Todos os direitos reservados."
   */
  textoCopyright?: string | null;
  /**
   * Aparece no rodapé para o cliente saber como pode pagar antes de chegar no carrinho. Separe com o sinal · ou com barra. Este texto é só informativo: quais pagamentos funcionam de verdade é definido no Mercado Pago, não aqui.
   */
  formasDePagamento?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * O conteúdo da página que conta a história da Elessar. É a página que abre quando o cliente clica em "Sobre a Loja" no rodapé do site. Tudo que você escrever aqui aparece lá assim que salvar.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pagina-sobre-nos".
 */
export interface PaginaSobreNo {
  id: number;
  /**
   * O texto grande no topo da página. Exemplo: "Sobre a Loja" ou "Nossa história".
   */
  titulo: string;
  /**
   * Uma ou duas linhas logo abaixo do título, em letra maior que o resto. Serve para resumir a loja em uma frase. Exemplo: "Discos selecionados a mão desde 2024." Pode deixar vazio — nesse caso a página começa direto no texto.
   */
  chamada?: string | null;
  /**
   * A história da loja, escrita normalmente. Use os botões no topo da caixa para deixar em negrito, criar títulos de seção ou fazer listas. Escreva em parágrafos curtos: fica mais fácil de ler no celular. Pode salvar pela metade e voltar depois.
   */
  texto?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Uma foto da loja, do acervo ou de você, exibida junto do texto. Opcional. Prefira uma foto deitada (mais larga que alta), com no mínimo 1600 pixels de largura.
   */
  imagem?: (number | null) | Media;
  /**
   * Blocos que aparecem embaixo do texto principal, na ordem em que estiverem aqui — arraste para reordenar. Use quando quiser separar assuntos, por exemplo "Como escolhemos os discos" ou "Onde nos encontrar". Se não precisar de nenhum, deixe vazio e a página mostra só o texto acima.
   */
  secoes?:
    | {
        /**
         * Aparece como um subtítulo. Exemplo: "Como escolhemos os discos".
         */
        titulo: string;
        texto: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        /**
         * Opcional. Aparece ao lado do texto desta seção.
         */
        imagem?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * As páginas que explicam as regras da loja ao cliente: como comprar, prazos de entrega, trocas, privacidade e termos de uso. Escolha a aba da página que quer mexer. O que você escrever passa a valer no site assim que salvar, então releia antes.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "paginas-legais".
 */
export interface PaginasLegai {
  id: number;
  /**
   * O número da versão das regras que valem hoje. Ele é gravado na conta de cada cliente no momento do cadastro, junto com a data e o texto exato que ele aceitou. MUDE ESTE NÚMERO sempre que alterar algo importante nos Termos de Uso ou na Política de Privacidade (por exemplo: de 1.0 para 1.1): quem se cadastrou com a versão antiga passa a ser tratado como pendente de novo aceite, e a loja pede a concordância na próxima vez que a pessoa entrar. Corrigir uma vírgula ou um erro de digitação não exige mudar a versão.
   */
  versaoDosTermos?: string | null;
  comoComprar: {
    /**
     * O texto grande no topo da página. Exemplo: "Como comprar".
     */
    titulo: string;
    /**
     * Explique o caminho da compra em passos curtos e numerados: escolher o produto, calcular o frete, pagar, receber. Diga quais formas de pagamento você aceita. Use a lista numerada dos botões acima — fica muito mais fácil de seguir que um texto corrido. Enquanto estiver vazio, esta página não aparece no site — dá para escrever aos poucos e salvar quantas vezes quiser.
     */
    texto?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    /**
     * Aparece no fim da página como "Última atualização". Mude sempre que alterar as regras: é o que mostra ao cliente qual versão valia quando ele comprou, e é a sua defesa numa discussão. Pode deixar vazio.
     */
    atualizadoEm?: string | null;
  };
  entrega: {
    /**
     * O texto grande no topo da página. Exemplo: "Entrega e frete".
     */
    titulo: string;
    /**
     * Fale de embalagem, prazo de postagem e rastreio. Seja concreto com os prazos — "postamos em até 2 dias úteis" vale mais que "enviamos rapidamente", e é o que evita reclamação. Não prometa prazo dos Correios, que não depende de você. Enquanto estiver vazio, esta página não aparece no site — dá para escrever aos poucos e salvar quantas vezes quiser.
     */
    texto?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    /**
     * Aparece no fim da página como "Última atualização". Mude sempre que alterar as regras: é o que mostra ao cliente qual versão valia quando ele comprou, e é a sua defesa numa discussão. Pode deixar vazio.
     */
    atualizadoEm?: string | null;
  };
  trocas: {
    /**
     * O texto grande no topo da página. Exemplo: "Trocas e devoluções".
     */
    titulo: string;
    /**
     * Diga o prazo para desistir da compra, em que estado o produto precisa voltar e por onde o cliente pede. Lembre que o Código de Defesa do Consumidor garante 7 dias corridos para arrependimento em compra pela internet — você pode dar mais, nunca menos. Enquanto estiver vazio, esta página não aparece no site — dá para escrever aos poucos e salvar quantas vezes quiser.
     */
    texto?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    /**
     * Aparece no fim da página como "Última atualização". Mude sempre que alterar as regras: é o que mostra ao cliente qual versão valia quando ele comprou, e é a sua defesa numa discussão. Pode deixar vazio.
     */
    atualizadoEm?: string | null;
  };
  privacidade: {
    /**
     * O texto grande no topo da página. Exemplo: "Política de Privacidade".
     */
    titulo: string;
    /**
     * Explique quais dados você guarda (nome, e-mail, endereço, CPF), para que servem (entregar o pedido e emitir a etiqueta) e com quem são compartilhados (Correios ou transportadora, e o Mercado Pago no pagamento). Diga também como o cliente pede para apagar os dados dele. Enquanto estiver vazio, esta página não aparece no site — dá para escrever aos poucos e salvar quantas vezes quiser.
     */
    texto?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    /**
     * Aparece no fim da página como "Última atualização". Mude sempre que alterar as regras: é o que mostra ao cliente qual versão valia quando ele comprou, e é a sua defesa numa discussão. Pode deixar vazio.
     */
    atualizadoEm?: string | null;
  };
  termos: {
    /**
     * O texto grande no topo da página. Exemplo: "Termos de Uso".
     */
    titulo: string;
    /**
     * As condições para usar o site e comprar: quem pode criar conta, o que acontece se um produto anunciado acabar, e o que a loja não se responsabiliza. Escreva em linguagem simples — termo que ninguém entende não protege ninguém. Enquanto estiver vazio, esta página não aparece no site — dá para escrever aos poucos e salvar quantas vezes quiser.
     */
    texto?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    /**
     * Aparece no fim da página como "Última atualização". Mude sempre que alterar as regras: é o que mostra ao cliente qual versão valia quando ele comprou, e é a sua defesa numa discussão. Pode deixar vazio.
     */
    atualizadoEm?: string | null;
  };
  cookies: {
    /**
     * O texto grande no topo da página. Exemplo: "Política de Cookies".
     */
    titulo: string;
    /**
     * Explique quais cookies o site usa e para quê: os que fazem o carrinho e o login funcionarem (sem eles a loja não funciona), e os de medição de audiência, se você usar. Diga como o cliente desliga os opcionais e o que ele perde ao desligar. Enquanto estiver vazio, esta página não aparece no site — dá para escrever aos poucos e salvar quantas vezes quiser.
     */
    texto?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    /**
     * Aparece no fim da página como "Última atualização". Mude sempre que alterar as regras: é o que mostra ao cliente qual versão valia quando ele comprou, e é a sua defesa numa discussão. Pode deixar vazio.
     */
    atualizadoEm?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * A lista de perguntas e respostas do site. Toda vez que um cliente perguntar a mesma coisa pela terceira vez, a resposta merece entrar aqui — cada pergunta bem respondida é uma mensagem a menos para você responder à mão. Esta página ainda está sendo montada no site; pode preencher desde já, que ela aparece assim que entrar no ar.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "perguntas-frequentes".
 */
export interface PerguntasFrequente {
  id: number;
  /**
   * O texto grande no topo da página. Exemplo: "Perguntas Frequentes".
   */
  titulo: string;
  /**
   * Uma ou duas linhas antes da lista. Bom lugar para dizer o que fazer quando a dúvida não estiver na lista. Exemplo: "Não achou sua dúvida? Chame a gente no WhatsApp." Pode deixar vazio.
   */
  introducao?: string | null;
  /**
   * Aparecem no site na mesma ordem que estiverem aqui — arraste pela alça à esquerda para reordenar. Deixe as dúvidas mais comuns em cima. Para tirar uma pergunta do ar, apague a linha inteira.
   */
  perguntas?:
    | {
        /**
         * Escreva do jeito que o cliente perguntaria, não do jeito técnico. "Em quanto tempo chega?" funciona melhor que "Prazo de entrega".
         */
        pergunta: string;
        /**
         * Responda direto na primeira frase e só depois explique. Se a resposta completa estiver em outra página, use o botão de link para mandar o cliente para lá.
         */
        resposta: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Parâmetros do cálculo de frete (origem, caixa padrão e acréscimo). As transportadoras exibidas ao cliente — PAC, SEDEX, Jadlog, Loggi — são as que estiverem ATIVAS no painel da SuperFrete (Integrações → Configurações da integração). Ligue ou desligue por lá; aqui não há nada a configurar sobre isso.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "configuracoes-de-frete".
 */
export interface ConfiguracoesDeFrete {
  id: number;
  /**
   * CEP de onde os pedidos são enviados.
   */
  cepOrigem: string;
  /**
   * Dados de quem envia — aparecem na etiqueta dos Correios. TODOS são obrigatórios: sem eles a etiqueta não é gerada automaticamente quando um pedido é pago. (O CEP é o "CEP de origem" acima.)
   */
  remetente: {
    nome: string;
    /**
     * Somente números, 11 (CPF) ou 14 (CNPJ) dígitos.
     */
    documento: string;
    telefone: string;
    email: string;
    rua: string;
    numero: string;
    complemento?: string | null;
    bairro: string;
    cidade: string;
    uf: string;
  };
  /**
   * Valor somado a cada opção de frete, já embutido. Não aparece separado para o cliente.
   */
  acrescimoFrete: number;
  /**
   * Usada como tamanho mínimo do pacote.
   */
  caixaPadrao?: {
    comprimento?: number | null;
    largura?: number | null;
    altura?: number | null;
  };
  /**
   * Usado quando um disco não tem peso cadastrado.
   */
  pesoPadraoItem?: number | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Controla o e-mail que avisa o cliente quando alguém entra na conta dele. Serve para a pessoa perceber rápido se outra pessoa descobriu a senha.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seguranca-da-conta".
 */
export interface SegurancaDaConta {
  id: number;
  /**
   * Ligado, o cliente recebe um e-mail quando a conta é acessada de um aparelho ou lugar novo. É a forma mais simples de alguém descobrir que a conta foi invadida. Desligue apenas se estiver gerando reclamação.
   */
  avisarNovoAcesso?: boolean | null;
  /**
   * O cliente NÃO recebe e-mail toda vez que entra: só quando o aparelho é novo, ou quando passou este número de dias desde o último aviso naquele aparelho. Com 30, quem entra todo dia do mesmo computador recebe no máximo um aviso por mês. Diminuir aumenta a vigilância e o número de e-mails; aumentar faz o contrário.
   */
  diasParaAvisarDeNovo?: number | null;
  /**
   * O histórico que aparece no cadastro do cliente, para você conseguir responder "de onde andaram entrando nesta conta?" quando alguém reclamar. Os mais antigos são descartados automaticamente.
   */
  quantosAcessosGuardar?: number | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  banners?: T;
  tempoDoCarrossel?: T;
  featuredRecords?: T;
  exclusiveReleases?: T;
  bandIcons?:
    | T
    | {
        image?: T;
        artist?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "configuracoes-gerais_select".
 */
export interface ConfiguracoesGeraisSelect<T extends boolean = true> {
  nomeDaLoja?: T;
  tagline?: T;
  emailContato?: T;
  telefone?: T;
  endereco?: T;
  horarioAtendimento?: T;
  instagram?: T;
  youtube?: T;
  facebook?: T;
  razaoSocial?: T;
  cnpj?: T;
  avisoAtivo?: T;
  avisoTexto?: T;
  avisoLink?: T;
  avisoValidoAte?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "whatsapp_select".
 */
export interface WhatsappSelect<T extends boolean = true> {
  ativo?: T;
  numero?: T;
  mensagemPadrao?: T;
  mensagemNoProduto?: T;
  textoDoBotao?: T;
  horarioAtendimento?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rodape_select".
 */
export interface RodapeSelect<T extends boolean = true> {
  colunas?:
    | T
    | {
        titulo?: T;
        links?:
          | T
          | {
              texto?: T;
              endereco?: T;
              id?: T;
            };
        id?: T;
      };
  textoCopyright?: T;
  formasDePagamento?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pagina-sobre-nos_select".
 */
export interface PaginaSobreNosSelect<T extends boolean = true> {
  titulo?: T;
  chamada?: T;
  texto?: T;
  imagem?: T;
  secoes?:
    | T
    | {
        titulo?: T;
        texto?: T;
        imagem?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "paginas-legais_select".
 */
export interface PaginasLegaisSelect<T extends boolean = true> {
  versaoDosTermos?: T;
  comoComprar?:
    | T
    | {
        titulo?: T;
        texto?: T;
        atualizadoEm?: T;
      };
  entrega?:
    | T
    | {
        titulo?: T;
        texto?: T;
        atualizadoEm?: T;
      };
  trocas?:
    | T
    | {
        titulo?: T;
        texto?: T;
        atualizadoEm?: T;
      };
  privacidade?:
    | T
    | {
        titulo?: T;
        texto?: T;
        atualizadoEm?: T;
      };
  termos?:
    | T
    | {
        titulo?: T;
        texto?: T;
        atualizadoEm?: T;
      };
  cookies?:
    | T
    | {
        titulo?: T;
        texto?: T;
        atualizadoEm?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "perguntas-frequentes_select".
 */
export interface PerguntasFrequentesSelect<T extends boolean = true> {
  titulo?: T;
  introducao?: T;
  perguntas?:
    | T
    | {
        pergunta?: T;
        resposta?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "configuracoes-de-frete_select".
 */
export interface ConfiguracoesDeFreteSelect<T extends boolean = true> {
  cepOrigem?: T;
  remetente?:
    | T
    | {
        nome?: T;
        documento?: T;
        telefone?: T;
        email?: T;
        rua?: T;
        numero?: T;
        complemento?: T;
        bairro?: T;
        cidade?: T;
        uf?: T;
      };
  acrescimoFrete?: T;
  caixaPadrao?:
    | T
    | {
        comprimento?: T;
        largura?: T;
        altura?: T;
      };
  pesoPadraoItem?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seguranca-da-conta_select".
 */
export interface SegurancaDaContaSelect<T extends boolean = true> {
  avisarNovoAcesso?: T;
  diasParaAvisarDeNovo?: T;
  quantosAcessosGuardar?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}